# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(451, 710)
        Form.setStyleSheet("MainWindow{\n"
"background:#e7e7e7;\n"
"\n"
"}")
        self.ACButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("AC"))
        self.ACButton.setGeometry(QtCore.QRect(10, 160, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ACButton.setFont(font)
        self.ACButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ACButton.setAutoFillBackground(False)
        self.ACButton.setStyleSheet("#ACButton{\n"
"border:0px;\n"
"background:#e6e6e6;\n"
"}\n"
"#ACButton:hover{\n"
"background:#ffab6e;\n"
"border:2px solid #fff;\n"
"}\n"
"")
        self.ACButton.setText("AC")
        self.ACButton.setObjectName("ACButton")
        self.deleteButton = QtWidgets.QPushButton(Form, clicked= lambda: self.remove_it())
        self.deleteButton.setGeometry(QtCore.QRect(120, 160, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.deleteButton.setFont(font)
        self.deleteButton.setStyleSheet("#deleteButton{\n"
"border:0px;\n"
"background:#e6e6e6;\n"
"}\n"
"#deleteButton:hover{\n"
"background:#8ee5ff;\n"
"border:2px solid #fff;\n"
"}")
        self.deleteButton.setText("<<")
        self.deleteButton.setObjectName("deleteButton")
        self.percentButton = QtWidgets.QPushButton(Form, clicked= lambda: self.percent_it())
        self.percentButton.setGeometry(QtCore.QRect(240, 160, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.percentButton.setFont(font)
        self.percentButton.setStyleSheet("#percentButton{\n"
"border:0px;\n"
"background:#e6e6e6;\n"
"}\n"
"#percentButton:hover{\n"
"background:#bebebe;\n"
"border:2px solid #fff;\n"
"}")
        self.percentButton.setText("%")
        self.percentButton.setObjectName("percentButton")
        self.divideButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("/"))
        self.divideButton.setGeometry(QtCore.QRect(350, 160, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.divideButton.setFont(font)
        self.divideButton.setStyleSheet("#divideButton{\n"
"border:0px;\n"
"background:#e6e6e6;\n"
"}\n"
"#divideButton:hover{\n"
"background:#bebebe;\n"
"border:2px solid #fff;\n"
"}")
        self.divideButton.setText("/")
        self.divideButton.setObjectName("divideButton")
        self.sevenButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("7"))
        self.sevenButton.setGeometry(QtCore.QRect(10, 270, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sevenButton.setFont(font)
        self.sevenButton.setStyleSheet("#sevenButton{\n"
"border:0px;\n"
"background:#fff;\n"
"}\n"
"#sevenButton:hover{\n"
"background:#bebebe;\n"
"border:2px solid #fff;\n"
"}")
        self.sevenButton.setText("7")
        self.sevenButton.setObjectName("sevenButton")
        self.nineButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("9"))
        self.nineButton.setGeometry(QtCore.QRect(240, 270, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nineButton.setFont(font)
        self.nineButton.setStyleSheet("#nineButton{\n"
"border:0px;\n"
"background:#fff;\n"
"}\n"
"#nineButton:hover{\n"
"background:#bebebe;\n"
"border:2px solid #fff;\n"
"}")
        self.nineButton.setText("9")
        self.nineButton.setObjectName("nineButton")
        self.multiButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("*"))
        self.multiButton.setGeometry(QtCore.QRect(350, 270, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.multiButton.setFont(font)
        self.multiButton.setStyleSheet("#multiButton{\n"
"border:0px;\n"
"background:#e6e6e6;\n"
"}\n"
"#multiButton:hover{\n"
"background:#bebebe;\n"
"border:2px solid #fff;\n"
"}")
        self.multiButton.setText("x")
        self.multiButton.setObjectName("multiButton")
        self.eightButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("8"))
        self.eightButton.setGeometry(QtCore.QRect(120, 270, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.eightButton.setFont(font)
        self.eightButton.setStyleSheet("#eightButton{\n"
"border:0px;\n"
"background:#fff;\n"
"}\n"
"#eightButton:hover{\n"
"background:#bebebe;\n"
"border:2px solid #fff;\n"
"}")
        self.eightButton.setText("8")
        self.eightButton.setObjectName("eightButton")
        self.fourButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("4"))
        self.fourButton.setGeometry(QtCore.QRect(10, 380, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.fourButton.setFont(font)
        self.fourButton.setStyleSheet("#fourButton{\n"
"border:0px;\n"
"background:#fff;\n"
"}\n"
"#fourButton:hover{\n"
"background:#bebebe;\n"
"border:2px solid #fff;\n"
"}")
        self.fourButton.setText("4")
        self.fourButton.setObjectName("fourButton")
        self.sixButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("6"))
        self.sixButton.setGeometry(QtCore.QRect(240, 380, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sixButton.setFont(font)
        self.sixButton.setStyleSheet("#sixButton{\n"
"border:0px;\n"
"background:#fff;\n"
"}\n"
"#sixButton:hover{\n"
"background:#bebebe;\n"
"border:2px solid #fff;\n"
"}")
        self.sixButton.setText("6")
        self.sixButton.setObjectName("sixButton")
        self.minusButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("-"))
        self.minusButton.setGeometry(QtCore.QRect(350, 380, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.minusButton.setFont(font)
        self.minusButton.setStyleSheet("#minusButton{\n"
"border:0px;\n"
"background:#e6e6e6;\n"
"}\n"
"#minusButton:hover{\n"
"background:#bebebe;\n"
"border:2px solid #fff;\n"
"}")
        self.minusButton.setText("-")
        self.minusButton.setObjectName("minusButton")
        self.fiveButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("5"))
        self.fiveButton.setGeometry(QtCore.QRect(120, 380, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.fiveButton.setFont(font)
        self.fiveButton.setStyleSheet("#fiveButton{\n"
"border:0px;\n"
"background:#fff;\n"
"}\n"
"#fiveButton:hover{\n"
"background:#bebebe;\n"
"border:2px solid #fff;\n"
"}")
        self.fiveButton.setText("5")
        self.fiveButton.setObjectName("fiveButton")
        self.oneButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("1"))
        self.oneButton.setGeometry(QtCore.QRect(10, 490, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.oneButton.setFont(font)
        self.oneButton.setStyleSheet("#oneButton{\n"
"border:0px;\n"
"background:#fff;\n"
"}\n"
"#oneButton:hover{\n"
"background:#bebebe;\n"
"border:2px solid #fff;\n"
"}")
        self.oneButton.setText("1")
        self.oneButton.setObjectName("oneButton")
        self.threeButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("3"))
        self.threeButton.setGeometry(QtCore.QRect(240, 490, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.threeButton.setFont(font)
        self.threeButton.setStyleSheet("#threeButton{\n"
"border:0px;\n"
"background:#fff;\n"
"}\n"
"#threeButton:hover{\n"
"background:#bebebe;\n"
"border:2px solid #fff;\n"
"}")
        self.threeButton.setText("3")
        self.threeButton.setObjectName("threeButton")
        self.plusButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("+"))
        self.plusButton.setGeometry(QtCore.QRect(350, 490, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.plusButton.setFont(font)
        self.plusButton.setStyleSheet("#plusButton{\n"
"border:0px;\n"
"background:#e6e6e6;\n"
"}\n"
"#plusButton:hover{\n"
"background:#bebebe;\n"
"border:2px solid #fff;\n"
"}")
        self.plusButton.setText("+")
        self.plusButton.setObjectName("plusButton")
        self.twoButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("2"))
        self.twoButton.setGeometry(QtCore.QRect(120, 490, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.twoButton.setFont(font)
        self.twoButton.setStyleSheet("#twoButton{\n"
"border:0px;\n"
"background:#fff;\n"
"}\n"
"#twoButton:hover{\n"
"background:#bebebe;\n"
"border:2px solid #fff;\n"
"}")
        self.twoButton.setText("2")
        self.twoButton.setObjectName("twoButton")
        self.dotButton = QtWidgets.QPushButton(Form, clicked= lambda: self.dot_it())
        self.dotButton.setGeometry(QtCore.QRect(240, 600, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.dotButton.setFont(font)
        self.dotButton.setStyleSheet("#dotButton{\n"
"border:0px;\n"
"background:#e6e6e6;\n"
"}\n"
"#dotButton:hover{\n"
"background:#bebebe;\n"
"border:2px solid #fff;\n"
"}")
        self.dotButton.setText(".")
        self.dotButton.setObjectName("dotButton")
        self.equalButton = QtWidgets.QPushButton(Form, clicked= lambda: self.math_it())
        self.equalButton.setGeometry(QtCore.QRect(350, 600, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.equalButton.setFont(font)
        self.equalButton.setStyleSheet("#equalButton{\n"
"border:0px;\n"
"background:#93ffa5;\n"
"}\n"
"#equalButton:hover{\n"
"background:#7eda8d;\n"
"border:2px solid #fff;\n"
"color:#fff;\n"
"}")
        self.equalButton.setText("=")
        self.equalButton.setObjectName("equalButton")
        self.plus_minusButton = QtWidgets.QPushButton(Form, clicked= lambda: self.plusminus_it())
        self.plus_minusButton.setGeometry(QtCore.QRect(10, 600, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.plus_minusButton.setFont(font)
        self.plus_minusButton.setStyleSheet("#plus_minusButton{\n"
"border:0px;\n"
"background:#e6e6e6;\n"
"}\n"
"#plus_minusButton:hover{\n"
"background:#bebebe;\n"
"border:2px solid #fff;\n"
"}")
        self.plus_minusButton.setText("+/-")
        self.plus_minusButton.setObjectName("plus_minusButton")
        self.zeroButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("0"))
        self.zeroButton.setGeometry(QtCore.QRect(120, 600, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.zeroButton.setFont(font)
        self.zeroButton.setStyleSheet("#zeroButton{\n"
"border:0px;\n"
"background:#fff;\n"
"}\n"
"#zeroButton:hover{\n"
"background:#bebebe;\n"
"border:2px solid #fff;\n"
"}")
        self.zeroButton.setText("0")
        self.zeroButton.setObjectName("zeroButton")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 431, 141))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("#lineEdit{\n"
"background: #e6e6e6;\n"
"border:0px;\n"
"color:black;\n"
"font-size:50px;\n"
"}")
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calculator"))
        self.ACButton.setShortcut(_translate("Form", "Esc"))
        self.deleteButton.setShortcut(_translate("Form", "Backspace"))
        self.percentButton.setShortcut(_translate("Form", "%"))
        self.divideButton.setShortcut(_translate("Form", "/"))
        self.sevenButton.setShortcut(_translate("Form", "7"))
        self.nineButton.setShortcut(_translate("Form", "9"))
        self.multiButton.setShortcut(_translate("Form", "*"))
        self.eightButton.setShortcut(_translate("Form", "8"))
        self.fourButton.setShortcut(_translate("Form", "4"))
        self.sixButton.setShortcut(_translate("Form", "6"))
        self.minusButton.setShortcut(_translate("Form", "-"))
        self.fiveButton.setShortcut(_translate("Form", "5"))
        self.oneButton.setShortcut(_translate("Form", "1"))
        self.threeButton.setShortcut(_translate("Form", "3"))
        self.plusButton.setShortcut(_translate("Form", "+"))
        self.twoButton.setShortcut(_translate("Form", "2"))
        self.dotButton.setShortcut(_translate("Form", "."))
        self.equalButton.setShortcut(_translate("Form", "Enter"))
        self.zeroButton.setShortcut(_translate("Form", "0"))
        self.lineEdit.setPlaceholderText(_translate("Form", "0"))
        
    def percent_it(self):
        screen =  self.lineEdit.text()
        if len(screen) == 0 :return
        try:
                result = eval(screen) / 100
                self.lineEdit.setText(str(result))
        except:
                self.lineEdit.setText("ERROR")



    def math_it(self):
        screen = self.lineEdit.text()
        try:
            answer = eval(screen)
            if answer % 1 == 0:
                answer = int(answer)
            else:
                answer = round(answer, 5)
            self.lineEdit.setText(str(answer))
        except:
            self.lineEdit.setText("ERROR")

    def plusminus_it(self):
        screen = self.lineEdit.text()
        if "-" in screen:
            self.lineEdit.setText(screen.replace("-", ""))
        else:
            self.lineEdit.setText(f'-{screen}')

    def remove_it(self):
        screen = self.lineEdit.text()
        screen = screen[:-1]
        self.lineEdit.setText(screen)

    def dot_it(self):
        screen = self.lineEdit.text()
        num_plus = screen.split("+")
        num_minus = screen.split("-")
        num_multi = screen.split("*")
        num_divide = screen.split("/")
        if "+" in screen and "." not in num_plus[-1] or "-" in screen and "." not in num_minus[-1] or "*" in screen and "." not in num_multi[-1] or "/" in screen and "." not in num_divide[-1]:
            self.lineEdit.setText(f'{screen}.')
        if "." in screen:
            pass
        else:
            self.lineEdit.setText(f'{screen}.')

    def press_it(self, pressed):
        screen = self.lineEdit.text()
        if pressed == "AC":
            self.lineEdit.setText("")
        elif "ERROR" in screen:
            self.lineEdit.setText("")
            self.lineEdit.setText(f'{self.lineEdit.text()}{pressed}')
        elif screen == "0":
            self.lineEdit.setText("")
            self.lineEdit.setText(f'{self.lineEdit.text()}{pressed}')
        else:
            self.lineEdit.setText(f'{self.lineEdit.text()}{pressed}')
            



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
