# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(451, 697)
        self.OutputLabel = QtWidgets.QLabel(Form)
        self.OutputLabel.setGeometry(QtCore.QRect(10, 10, 431, 141))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.OutputLabel.setFont(font)
        self.OutputLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.OutputLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.OutputLabel.setLineWidth(0)
        self.OutputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.OutputLabel.setObjectName("OutputLabel")
        self.ACButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("AC"))
        self.ACButton.setGeometry(QtCore.QRect(10, 160, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ACButton.setFont(font)
        self.ACButton.setText("AC")
        self.ACButton.setObjectName("ACButton")
        self.plus_minusButton = QtWidgets.QPushButton(Form, clicked= lambda: self.plusminus_it())
        self.plus_minusButton.setGeometry(QtCore.QRect(120, 160, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.plus_minusButton.setFont(font)
        self.plus_minusButton.setText("+/-")
        self.plus_minusButton.setObjectName("plus_minusButton")
        self.percentButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("%"))
        self.percentButton.setGeometry(QtCore.QRect(240, 160, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.percentButton.setFont(font)
        self.percentButton.setText("%")
        self.percentButton.setObjectName("percentButton")
        self.divideButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("/"))
        self.divideButton.setGeometry(QtCore.QRect(350, 160, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.divideButton.setFont(font)
        self.divideButton.setText("/")
        self.divideButton.setObjectName("divideButton")
        self.sevenButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("7"))
        self.sevenButton.setGeometry(QtCore.QRect(10, 270, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sevenButton.setFont(font)
        self.sevenButton.setText("7")
        self.sevenButton.setObjectName("sevenButton")
        self.nineButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("9"))
        self.nineButton.setGeometry(QtCore.QRect(240, 270, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nineButton.setFont(font)
        self.nineButton.setText("9")
        self.nineButton.setObjectName("nineButton")
        self.multiButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("*"))
        self.multiButton.setGeometry(QtCore.QRect(350, 270, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.multiButton.setFont(font)
        self.multiButton.setText("X")
        self.multiButton.setObjectName("multiButton")
        self.eightButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("8"))
        self.eightButton.setGeometry(QtCore.QRect(120, 270, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.eightButton.setFont(font)
        self.eightButton.setText("8")
        self.eightButton.setObjectName("eightButton")
        self.fourButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("4"))
        self.fourButton.setGeometry(QtCore.QRect(10, 380, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.fourButton.setFont(font)
        self.fourButton.setText("4")
        self.fourButton.setObjectName("fourButton")
        self.sixButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("6"))
        self.sixButton.setGeometry(QtCore.QRect(240, 380, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sixButton.setFont(font)
        self.sixButton.setText("6")
        self.sixButton.setObjectName("sixButton")
        self.minusButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("-"))
        self.minusButton.setGeometry(QtCore.QRect(350, 380, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.minusButton.setFont(font)
        self.minusButton.setText("-")
        self.minusButton.setObjectName("minusButton")
        self.fiveButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("5"))
        self.fiveButton.setGeometry(QtCore.QRect(120, 380, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.fiveButton.setFont(font)
        self.fiveButton.setText("5")
        self.fiveButton.setObjectName("fiveButton")
        self.oneButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("1"))
        self.oneButton.setGeometry(QtCore.QRect(10, 490, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.oneButton.setFont(font)
        self.oneButton.setText("1")
        self.oneButton.setObjectName("oneButton")
        self.threeButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("3"))
        self.threeButton.setGeometry(QtCore.QRect(240, 490, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.threeButton.setFont(font)
        self.threeButton.setText("3")
        self.threeButton.setObjectName("threeButton")
        self.plusButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("+"))
        self.plusButton.setGeometry(QtCore.QRect(350, 490, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.plusButton.setFont(font)
        self.plusButton.setText("+")
        self.plusButton.setObjectName("plusButton")
        self.twoButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("2"))
        self.twoButton.setGeometry(QtCore.QRect(120, 490, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.twoButton.setFont(font)
        self.twoButton.setText("2")
        self.twoButton.setObjectName("twoButton")
        self.dotButton = QtWidgets.QPushButton(Form, clicked= lambda: self.dot_it())
        self.dotButton.setGeometry(QtCore.QRect(240, 600, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.dotButton.setFont(font)
        self.dotButton.setText(".")
        self.dotButton.setObjectName("dotButton")
        self.equalButton = QtWidgets.QPushButton(Form, clicked= lambda: self.math_it())
        self.equalButton.setGeometry(QtCore.QRect(350, 600, 91, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.equalButton.setFont(font)
        self.equalButton.setText("=")
        self.equalButton.setObjectName("equalButton")
        self.zeroButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it("0"))
        self.zeroButton.setGeometry(QtCore.QRect(10, 600, 201, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.zeroButton.setFont(font)
        self.zeroButton.setText("0")
        self.zeroButton.setObjectName("zeroButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def math_it(self):
        screen = self.OutputLabel.text()
        try:
            answer = eval(screen)
            answer = round(answer, 8)
            self.OutputLabel.setText(str(answer))
        except:
            self.OutputLabel.setText("ERROR")

    def plusminus_it(self):
        screen = self.OutputLabel.text()
        if "-" in screen:
            self.OutputLabel.setText(screen.replace("-", ""))
        else:
            self.OutputLabel.setText(f'-{screen}')

    def remove_it(self):
        screen = self.OutputLabel.text()
        screen = screen[:-1]
        self.OutputLabel.setText(screen)

    def dot_it(self):
        screen = self.OutputLabel.text()
        if screen[-1] == ".":
            pass
        else:
            self.OutputLabel.setText(f'{screen}.')

    
    def press_it(self,pressed):
        if pressed == "AC":
            self.OutputLabel.setText("0")
        else:
            if self.OutputLabel.text() == "0":
                self.OutputLabel.setText("")
                self.ACButton.setText("C")
            self.OutputLabel.setText(f'{self.OutputLabel.text()}{pressed}')
            
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calculator"))
        self.OutputLabel.setText(_translate("Form", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
